name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build_and_push_image:
    uses: ./.github/workflows/build.yml
    with:
      push: true
      tags: |
        ghcr.io/${{ github.repository_owner }}/ipt-netflow-exporter:latest
        ghcr.io/${{ github.repository_owner }}/ipt-netflow-exporter:${{ github.ref_name }}
      go_version: ${{ vars.GO_VERSION }}
